apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dpu-operator-daemon
  namespace: {{.Namespace}}
spec:
  selector:
    matchLabels:
      app: dpu-operator-daemon
  template:
    metadata:
      labels:
        app: dpu-operator-daemon
        component: network
        type: infra
    spec:
      serviceAccountName: dpu-operator-daemon-sa
      hostNetwork: true
      hostPID: true
      nodeSelector:
        dpu: "true"
      securityContext:
        privileged: true
      containers:
      - name: dpu-operator-daemon
        image: {{.DpuOperatorDaemonImage}}
        securityContext:
          privileged: true
        imagePullPolicy: {{.ImagePullPolicy}}
        env:
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          value: {{.Namespace}}
        volumeMounts:
        - name: dpu-daemon-mount
          mountPath: /var/run/dpu-daemon
          mountPropagation: Bidirectional
        - name: cni-dir
          mountPath: /opt/cni/bin
        - name: host-run
          mountPath: /var/run/netns
          mountPropagation: Bidirectional
        - name: proc
          mountPath: /proc
        args:
        - --mode
        - {{.Mode}}
      volumes:
        - name: dpu-daemon-mount
          hostPath:
            path: /var/run/dpu-daemon
        - name: cni-dir
          hostPath:
            path: /var/lib/cni/bin/
        - name: host-run
          hostPath:
            path: /var/run/netns
        - name: proc
          hostPath:
            path: /proc/
