apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dpu-daemon-role
  namespace: {{.Namespace}}
rules:
- apiGroups:
    - security.openshift.io
  resourceNames:
    - privileged
  resources:
    - securitycontextconstraints
  verbs:
    - use
- apiGroups:
  - config.openshift.io
  resources:
  - servicefunctionchains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
