kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dpu-daemon-role-binding
  namespace: {{.Namespace}}
subjects:
- kind: ServiceAccount
  name: dpu-daemon-sa
roleRef:
  kind: Role
  name: dpu-daemon-role
  apiGroup: rbac.authorization.k8s.io

