# permissions for end users to view classifierconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: classifierconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dpu-operator
    app.kubernetes.io/part-of: dpu-operator
    app.kubernetes.io/managed-by: kustomize
  name: classifierconfig-viewer-role
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - classifierconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - classifierconfigs/status
  verbs:
  - get
