# permissions for end users to edit servicefunctionchains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: servicefunctionchain-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dpu-operator
    app.kubernetes.io/part-of: dpu-operator
    app.kubernetes.io/managed-by: kustomize
  name: servicefunctionchain-editor-role
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - servicefunctionchains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - servicefunctionchains/status
  verbs:
  - get
