apiVersion: config.openshift.io/v1
kind: ClassifierConfig
metadata:
  labels:
    app.kubernetes.io/name: classifierconfig
    app.kubernetes.io/instance: classifierconfig-sample
    app.kubernetes.io/part-of: dpu-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dpu-operator
  name: classifierconfig-sample
spec:
  # TODO(user): Add fields here
