## Append samples of your project ##
resources:
- config_v1_dpuoperatorconfig.yaml
- config_v1_classifierconfig.yaml
- config_v1_servicefunctionchain.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
