clusters:
  - name : "iso_cluster"
    api_vip: "192.168.122.99"
    ingress_vip: "192.168.122.101"
    network_api_port: "eno12409"
    kind: "iso"
    install_iso: "{{iso_server()}}/RHEL-9.6.0-20241114.6-aarch64-dvd1-w-kickstart.iso.v2"
    masters:
    - name: "{{worker_number(0)}}-acc"
      node: "localhost"
      kind: "ipu"
      bmc: "{{IMC_hostname(0)}}"
      bmc_user: "root"
      bmc_password: "redhat"
      host_side_bmc: "{{bmc(0)}}"
      ip: "172.16.3.16"
      mac: "{{IPU_mac_address(0)}}"
    postconfig:
    - name: "rh_subscription"
      organization_id: "{{organization_id()}}"
      activation_key: "{{activation_key()}}"
    - name: "microshift"
    - name: "dpu_operator_dpu"
      dpu_operator_path: "../../"
      ipu_plugin_sha: "0c23d7ef37bf7c5bfdb89958df080644fd5aea3b"
