clusters:
  - name : "ocpcluster"
    api_vip: "192.168.122.99"
    ingress_vip: "192.168.122.101"
    kubeconfig: "/root/kubeconfig.ocpcluster"
    version: "4.16.0-nightly"
    network_api_port: "eno12399"
    postconfig:
    - name: "dpu_operator_host"
      dpu_operator_path: "../../"
      ipu_plugin_sha: "0c23d7ef37bf7c5bfdb89958df080644fd5aea3b"
    masters:
    - name: "nicmodecluster-master-1"
      kind: "vm"
      node: "localhost"
      ip: "192.168.122.2"
      disk_size: 32
    - name: "nicmodecluster-master-2"
      kind: "vm"
      node: "localhost"
      ip: "192.168.122.3"
      disk_size: 32
    - name: "nicmodecluster-master-3"
      kind: "vm"
      node: "localhost"
      ip: "192.168.122.4"
      disk_size: 32
    workers:
    - name: "worker-{{worker_number(0)}}"
      kind: "physical"
      node: "{{worker_name(0)}}" 
      bmc_user: "root"
      bmc_password: "calvin"
      bmc: "{{bmc(0)}}"
